### PR TITLE
adding builds for linux/arm64/v8

### PR DESCRIPTION
**Pull request by bttnns**

### CODE REVIEW

**Comment by mikenye** [comment]
Hey @btannous, thanks so much for submitting this. 

It was my understanding that `linux/arm64` was the same as `linux/arm64/v8`. 

I tested your change this morning and the resulting image was identical to the `linux/arm64` variant and it built from the cache of the `linux/arm64` image. 

Furthermore, a `docker image inspect` showed the architecture as `linux/arm64`. 

What’s the use case for having `linux/arm64/v8`?

Thanks.

**Comment by bttnns** [comment]
Interesting. Thank you for checking it out quickly, and for the images :)

I’m using Fedora IoT on a Pi 3b+ which uses podman instead of docker.

For some reason it didn’t pull your image as it was looking for arm64/v8. I’m new to this combo, so maybe i’m missing something. 

I will try to specify the arm64 variant. I’ll check it out here in a bit.

**Comment by mikenye** [comment]
No worries at all. I'm happy to add `linux/arm64/v8` if it solves your problem mate. Just let me know.

**Comment by bttnns** [comment]
So it's looking like the plain `arm64` will work with an addtl flag.  I'll close the PRs! Sorry for the false alarm, but maybe these comments will help someone running into this issue.

http://docs.podman.io/en/latest/markdown/podman-pull.1.html

Adding: `--override-arch=arm64` seems to work, when podman is trying to look for `arm64/v8` specifically.

**Comment by mikenye** [comment]
Thanks for letting me know. I have subbed to the libpod case you opened.

Agree the architecture names are a mess. `armel`, `armhf`, `armv7l`, `aarch64`, `arm64`... It is not intuitive at all.

**Pull request closed without merging**
