### PR TITLE
Address issue #29

### PR DESCRIPTION
**Pull request by mikenye**

### CODE REVIEW

**Comment by klara31** [comment]
Is it just me, or are these issues not pushed to docker? I just updated, but do not see a healthcheck...

**Comment by mikenye** [comment]
Apologies, I've been dealing with a problem in my build cluster that I've just now resolved. Updated build should be on docker hub in the next few minutes. Sorry for the inconvenience.

**Comment by klara31** [comment]
Something went wrong, as the container keeps restarting since the update. Logging is empty...

**Comment by mikenye** [comment]
Acknowledging this. Something is wrong with my build farm. I'm actively troubleshooting this right now. Apologies for the inconvenience.

**Comment by klara31** [comment]
No problem. 
Maybe check pfclient as well, as it looks like it has the same issue...

**Comment by mikenye** [comment]
Thanks, I have. All my containers have an issue. I've nearly fixed everything up so not long to go.

**Comment by klara31** [comment]
I just updated pfclient, that one still seems to have this issue…

**Comment by mikenye** [comment]
@klara31 can you re-pull `mikenye/planefinder` and try it? It should be fixed.

**Comment by mikenye** [comment]
@klara31 `mikenye/piaware` should be fixed too.

**Comment by klara31** [comment]
Just did a ```docker-compose up -d```, piaware is working OK, pfclient still not. 
pfclient is on image ```sha256:c117e53ff8261df471c7990da0c0e7ef61feb7b7e8f74e3a06931d41215f9ca4```

**Comment by mikenye** [comment]
Thanks for the info, looking into it now. All other images should (hopefully) be fixed.

**Comment by klara31** [comment]
I appreciate your effort!

The other ones I am running seem to look OK.

**Comment by mikenye** [comment]
You're very welcome. I'm quite embarrassed this happened.... 🤦

**Comment by klara31** [comment]
No worries :)

**Comment by mikenye** [comment]
OK planefinder should be fixed.

**Comment by klara31** [comment]
How long before it's being published?

**Comment by mikenye** [comment]
It should be up now.

**Comment by klara31** [comment]
I’m afraid it’s not...

**Comment by mikenye** [comment]
What problem are you having with it? Can you post some output?

**Comment by klara31** [comment]
```
 # docker-compose up pfclient
piaware is up-to-date
Starting pfclient ... done
Attaching to pfclient
```
And then it exits...

Image: ```sha256:3fd89a49f769c578813404c235a8ce5464b583f3f92bf9fa171bd18138827ed0```

**Comment by mikenye** [comment]
Hi @klara31, I've tested this image on `armv7l`, `aarch64` and `x86_64` architectures, and can't reproduce your problem:

**`armv7l`**:
```
$ uname -m
armv7l

$ docker pull mikenye/planefinder:latest
latest: Pulling from mikenye/planefinder
Digest: sha256:2149aa3caa18a5f9f097d1b72daea79b811752c6db4a1fe0aa2416afe434cb5b
Status: Image is up to date for mikenye/planefinder:latest
docker.io/mikenye/planefinder:latest

$ docker run --rm -it -e TZ=Australia/Perth -e BEASTHOST=x.x.x.x -e LAT=xx.xxxxx -e LONG=xxx.xxxxx -e SHARECODE=xxxxxxxxxxxxx mikenye/planefinder:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-pfclient: executing...
[cont-init.d] 01-pfclient: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-06-10 01:47:13.268432 [-] pfclient (4.1.1 armhf) started with the following options:
2020-06-10 01:47:13.269450 [-]  connection_type = 1
2020-06-10 01:47:13.269471 [-]  tcp_address = x.x.x.x
2020-06-10 01:47:13.269491 [-]  tcp_port = 30005
2020-06-10 01:47:13.269510 [-]  data_format = 1
2020-06-10 01:47:13.269528 [-]  aircraft_timeout = 30
2020-06-10 01:47:13.269545 [-]  select_timeout = 10
2020-06-10 01:47:13.269563 [-]  web_server_port = 30053
2020-06-10 01:47:13.269584 [-]  user_latitude = xx.xxxxx
2020-06-10 01:47:13.269604 [-]  user_longitude = xxx.xxxxx
2020-06-10 01:47:13.270252 [V] Performing NTP sync (1.planefinder.pool.ntp.org)...
2020-06-10 01:47:13.271507 [-] Web server is now listening on: http://172.17.0.3:30053
2020-06-10 01:47:13.271507 [-] Echo port is now listening on: 172.17.0.3:30054
2020-06-10 01:47:13.272239 [-] TCP connection established: x.x.x.x:30005
2020-06-10 01:47:13.636384 [V] NTP sync succeeded with settings:
2020-06-10 01:47:13.636424 [V]  Stratum: 3
2020-06-10 01:47:13.636453 [V]  System clock time: 1591753633.6364
2020-06-10 01:47:13.636475 [V]  Corrected clock time: 1591753633.6309
2020-06-10 01:47:13.636497 [V]  NTP offset: -0.0055s
2020-06-10 01:47:25.862675 [-] User location has been verified.
2020-06-10 01:49:04.208678 [-] Successfully sent 250 aircraft updates across 10 packets (19.00KB)
```

**`aarch64`:**
```
$ uname -m
aarch64

$ docker pull mikenye/planefinder:latest
latest: Pulling from mikenye/planefinder
Digest: sha256:2149aa3caa18a5f9f097d1b72daea79b811752c6db4a1fe0aa2416afe434cb5b
Status: Image is up to date for mikenye/planefinder:latest
docker.io/mikenye/planefinder:latest

$ docker run --rm -it -e TZ=Australia/Perth -e BEASTHOST=x.x.x.x -e LAT=xx.xxxxx -e LONG=xxx.xxxxx -e SHARECODE=xxxxxxxxxxxxx mikenye/planefinder:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-pfclient: executing...
[cont-init.d] 01-pfclient: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-06-10 01:53:55.151416 [-] pfclient (4.1.1 armhf) started with the following options:
2020-06-10 01:53:55.158529 [-]  connection_type = 1
2020-06-10 01:53:55.158547 [-]  tcp_address = x.x.x.x
2020-06-10 01:53:55.158562 [-]  tcp_port = 30005
2020-06-10 01:53:55.158576 [-]  data_format = 1
2020-06-10 01:53:55.158588 [-]  aircraft_timeout = 30
2020-06-10 01:53:55.158601 [-]  select_timeout = 10
2020-06-10 01:53:55.158614 [-]  web_server_port = 30053
2020-06-10 01:53:55.158638 [-]  user_latitude = xx.xxxxx
2020-06-10 01:53:55.158655 [-]  user_longitude = xxx.xxxxx
2020-06-10 01:53:55.160461 [V] Performing NTP sync (2.planefinder.pool.ntp.org)...
2020-06-10 01:53:55.161087 [-] Echo port is now listening on: 172.17.0.3:30054
2020-06-10 01:53:55.161308 [-] TCP connection established: x.x.x.x:30005
2020-06-10 01:53:55.164747 [-] Web server is now listening on: http://172.17.0.3:30053
2020-06-10 01:53:58.970311 [V] NTP sync succeeded with settings:
2020-06-10 01:53:58.970430 [V]  Stratum: 2
2020-06-10 01:53:58.970488 [V]  System clock time: 1591754038.9703
2020-06-10 01:53:58.970557 [V]  Corrected clock time: 1591754038.9678
2020-06-10 01:53:58.970603 [V]  NTP offset: -0.0025s
2020-06-10 01:54:04.754808 [-] User location has been verified.
2020-06-10 01:55:45.704524 [-] Successfully sent 258 aircraft updates across 10 packets (21.00KB)
```

**`x86_64`:**
```
$ uname -m
x86_64

$ docker pull mikenye/planefinder:latest
latest: Pulling from mikenye/planefinder
Digest: sha256:2149aa3caa18a5f9f097d1b72daea79b811752c6db4a1fe0aa2416afe434cb5b
Status: Image is up to date for mikenye/planefinder:latest
docker.io/mikenye/planefinder:latest

$ docker run --rm -it -e TZ=Australia/Perth -e BEASTHOST=x.x.x.x -e LAT=xx.xxxxx -e LONG=xxx.xxxxx -e SHARECODE=xxxxxxxxxxxxx mikenye/planefinder:latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-pfclient: executing...
[cont-init.d] 01-pfclient: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2020-06-10 01:57:25.161694 [-] pfclient (4.1.1 i386) started with the following options:
2020-06-10 01:57:25.162766 [-]  connection_type = 1
2020-06-10 01:57:25.162773 [-]  tcp_address = x.x.x.x
2020-06-10 01:57:25.162778 [-]  tcp_port = 30005
2020-06-10 01:57:25.162783 [-]  data_format = 1
2020-06-10 01:57:25.162787 [-]  aircraft_timeout = 30
2020-06-10 01:57:25.162792 [-]  select_timeout = 10
2020-06-10 01:57:25.162796 [-]  web_server_port = 30053
2020-06-10 01:57:25.162803 [-]  user_latitude = xx.xxxxx
2020-06-10 01:57:25.162808 [-]  user_longitude = xxx.xxxxx
2020-06-10 01:57:25.163465 [V] Performing NTP sync (3.planefinder.pool.ntp.org)...
2020-06-10 01:57:25.163821 [-] Echo port is now listening on: 172.17.0.8:30054
2020-06-10 01:57:25.163830 [-] Web server is now listening on: http://172.17.0.8:30053
2020-06-10 01:57:25.163923 [-] TCP connection established: x.x.x.x:30005
2020-06-10 01:57:25.484451 [V] NTP sync succeeded with settings:
2020-06-10 01:57:25.484519 [V]  Stratum: 2
2020-06-10 01:57:25.484545 [V]  System clock time: 1591754245.4844
2020-06-10 01:57:25.484563 [V]  Corrected clock time: 1591754245.4861
2020-06-10 01:57:25.484580 [V]  NTP offset: 0.0016s
2020-06-10 01:57:36.380308 [-] User location has been verified.
2020-06-10 01:59:15.485630 [-] Successfully sent 275 aircraft updates across 10 packets (22.00KB)
```

Are you able to open an issue on the `mikenye/planefinder` repo and we can continue troubleshooting there?

Thanks.

**Comment by klara31** [comment]
watchtower updated the pfclient container 7 hours ago to image ```sha256:da9748c81779bcd0e6355889f9c4be3bb81803e094bac7012b53f15c35aafa03```

Now it's working...

**Comment by mikenye** [comment]
Yay! Fantastic. Thanks for letting me know.

**Pull request merged**
